package entities;
<<<<<<< HEAD:GluonFXDesktop_nuevo/src/main/java/entities/PayMethod.java
// Generated 25 ene. 2020 22:19:24 by Hibernate Tools 5.2.12.Final
=======
<<<<<<< HEAD
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final
=======
// Generated 30 ene. 2020 8:50:01 by Hibernate Tools 5.2.12.Final

>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/PayMethod.java

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PayMethod generated by hbm2java
 */
@Entity
@Table(name = "pay_method", catalog = "7057507_administration_db")
public class PayMethod implements java.io.Serializable {

	private Integer payMethodId;
	private String description;

	public PayMethod() {
	}

	public PayMethod(String description) {
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pay_method_id", unique = true, nullable = false)
	public Integer getPayMethodId() {
		return this.payMethodId;
	}

	public void setPayMethodId(Integer payMethodId) {
		this.payMethodId = payMethodId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
