package com.model.entities;
// Generated 30 ene. 2020 8:50:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.StringProperty;

/**
 * ConceptWorkOrder generated by hbm2java
 */
@Entity
@Table(name = "concept_work_order", catalog = "7057507_administration_db")
public class ConceptWorkOrder implements java.io.Serializable {

	private Integer id;
	private WorkOrder workOrder;
	private String description;
	private Double price;
	
	private IntegerProperty id_prop;
	private ObjectProperty<WorkOrder> workOrder_prop;
	private StringProperty description_prop;
	private DoubleProperty price_prop;

	public ConceptWorkOrder() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
		this.id_prop.set(id);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work_order_id")
	public WorkOrder getWorkOrder() {
		return this.workOrder;
	}

	public void setWorkOrder(WorkOrder workOrder) {
		this.workOrder = workOrder;
		this.workOrder_prop.set(workOrder);
	}

	@Column(name = "description", length = 600)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
		this.description_prop.set(description);
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
		this.price_prop.set(price);
	}



	public final IntegerProperty id_propProperty() {
		return this.id_prop;
	}
	

	public final ObjectProperty<WorkOrder> workOrder_propProperty() {
		return this.workOrder_prop;
	}
	


	public final StringProperty description_propProperty() {
		return this.description_prop;
	}
	

	public final DoubleProperty price_propProperty() {
		return this.price_prop;
	}
	
	

}
