package entities;
<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Product.java
// Generated 25 ene. 2020 22:19:24 by Hibernate Tools 5.2.12.Final

=======
<<<<<<< HEAD
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final
=======
// Generated 30 ene. 2020 8:50:01 by Hibernate Tools 5.2.12.Final
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Product.java

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "7057507_administration_db")
public class Product implements java.io.Serializable {

	private String productId;
	private String name;
	private String description;
	private Double price;
	private Integer stock;
	private String url;
<<<<<<< HEAD

	public Product() {
	}

	public Product(String productId) {
		this.productId = productId;
	}

	public Product(String productId, String name, String description, Double price, Integer stock, String url) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.url = url;
	}

=======
	private List<WorkOrderDetail> workOrderDetails = new ArrayList<WorkOrderDetail>(0);
	private List<BudgetDetail> budgetDetails = new ArrayList<BudgetDetail>(0);
	private List<InvoiceDetail> invoiceDetails = new ArrayList<InvoiceDetail>(0);

	public Product() {
	}

<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Product.java
	public Product(String productId, String name, String description, Double price, Integer stock, String url,
			List<WorkOrderDetail> workOrderDetails, List<BudgetDetail> budgetDetails, List<InvoiceDetail> invoiceDetails) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.url = url;
		this.workOrderDetails = workOrderDetails;
		this.budgetDetails = budgetDetails;
		this.invoiceDetails = invoiceDetails;
	}

=======
	
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Product.java
	@Id

<<<<<<< HEAD
	@Column(name = "product_id", unique = true, nullable = false, length = 30)
=======
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_id", length = 30)
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "url", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

<<<<<<< HEAD
=======
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<WorkOrderDetail> getWorkOrderDetails() {
		return this.workOrderDetails;
	}

	public void setWorkOrderDetails(List<WorkOrderDetail> workOrderDetails) {
		this.workOrderDetails = workOrderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<BudgetDetail> getBudgetDetails() {
		return this.budgetDetails;
	}

	public void setBudgetDetails(List<BudgetDetail> budgetDetails) {
		this.budgetDetails = budgetDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(List<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}
	
	@Override
	public String toString() {		
		return getName();
	}

<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Product.java
=======
	public final StringProperty name_propProperty() {
		return this.name_prop;
	}
	

	public final StringProperty description_propProperty() {
		return this.description_prop;
	}
	
	
	public final DoubleProperty price_propProperty() {
		return this.price_prop;
	}
	

	public final IntegerProperty stock_proProperty() {
		return this.stock_pro;
	}
	

	public final StringProperty url_propProperty() {
		return this.url_prop;
	}
	
	
	public final ListProperty<WorkOrderDetail> workOrderDetails_propProperty() {
		return this.workOrderDetails_prop;
	}
	

	public final ListProperty<BudgetDetail> budgetDetails_propProperty() {
		return this.budgetDetails_prop;
	}
	

	public final ListProperty<InvoiceDetail> invoiceDetails_propProperty() {
		return this.invoiceDetails_prop;
	}
	
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Product.java
}
