package entities;
<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Tax.java
// Generated 25 ene. 2020 22:19:24 by Hibernate Tools 5.2.12.Final

=======
<<<<<<< HEAD
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final
=======
// Generated 30 ene. 2020 8:50:01 by Hibernate Tools 5.2.12.Final
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Tax.java

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax", catalog = "7057507_administration_db")
public class Tax implements java.io.Serializable {

	private String taxId;
	private Double percentage;
	private String description;
<<<<<<< HEAD
=======
	private List<Budget> budgets = new ArrayList<Budget>(0);
	private List<WorkOrder> workOrders = new ArrayList<WorkOrder>(0);
	private List<Invoice> invoices = new ArrayList<Invoice>(0);
<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Tax.java
=======
	
	private IntegerProperty id_prop = new SimpleIntegerProperty();
	private StringProperty taxId_prop = new SimpleStringProperty(); 
	private DoubleProperty percentage_prop = new SimpleDoubleProperty(); 
	private StringProperty description_prop = new SimpleStringProperty(); 
	private ListProperty<Budget> budgets_prop = new SimpleListProperty<>();
	private ListProperty<WorkOrder> workOrders_prop = new SimpleListProperty<>();
	private ListProperty<Invoice> invoices_prop = new SimpleListProperty<>();
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Tax.java

	public Tax() {
	}

<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Tax.java
	public Tax(String taxId, Double percentage, String description, List<Budget> budgets, List<WorkOrder> workOrders,
			List<Invoice> invoices) {
		this.taxId = taxId;
		this.percentage = percentage;
		this.description = description;
		this.budgets = budgets;
		this.workOrders = workOrders;
		this.invoices = invoices;
	}

=======
<<<<<<< HEAD
	public Tax(String taxId) {
		this.taxId = taxId;
	}

	public Tax(String taxId, Double percentage, String description) {
		this.taxId = taxId;
		this.percentage = percentage;
		this.description = description;
	}

=======
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Tax.java
	@Id

<<<<<<< HEAD
	@Column(name = "tax_id", unique = true, nullable = false, length = 30)
=======
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tax_id", length = 30)
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
	public String getTaxId() {
		return this.taxId;
	}

	public void setTaxId(String taxId) {
		this.taxId = taxId;
	}

	@Column(name = "percentage", precision = 22, scale = 0)
	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

<<<<<<< HEAD
=======
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public List<Budget> getBudgets() {
		return this.budgets;
	}

	public void setBudgets(List<Budget> budgets) {
		this.budgets = budgets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public List<WorkOrder> getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(List<WorkOrder> workOrders) {
		this.workOrders = workOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public List<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(List<Invoice> invoices) {
		this.invoices = invoices;
	}

	@Override
	public String toString() {			
		return String.valueOf(getPercentage());
	}
<<<<<<< HEAD:GluonFXDesktop_viejo/src/main/java/entities/Tax.java
=======
	
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
>>>>>>> 90b2be75c01262763035c56e8493c45fa000fd63:GluonFXDesktop/src/main/java/entities/Tax.java
}
