package entities;
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BudgetDetailId generated by hbm2java
 */
@Embeddable
public class BudgetDetailId implements java.io.Serializable {

	private int budgetDetailId;
	private String productId;

	public BudgetDetailId() {
	}

	public BudgetDetailId(int budgetDetailId, String productId) {
		this.budgetDetailId = budgetDetailId;
		this.productId = productId;
	}

	@Column(name = "budget_detail_id", nullable = false)
	public int getBudgetDetailId() {
		return this.budgetDetailId;
	}

	public void setBudgetDetailId(int budgetDetailId) {
		this.budgetDetailId = budgetDetailId;
	}

	@Column(name = "product_id", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BudgetDetailId))
			return false;
		BudgetDetailId castOther = (BudgetDetailId) other;

		return (this.getBudgetDetailId() == castOther.getBudgetDetailId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBudgetDetailId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
