package entities;
// Generated 19 ene. 2020 16:41:53 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BudgetDetailId generated by hbm2java
 */
@Embeddable
public class BudgetDetailId implements java.io.Serializable {

	private int budgetId;
	private String productId;

	public BudgetDetailId() {
	}

	public BudgetDetailId(int budgetId, String productId) {
		this.budgetId = budgetId;
		this.productId = productId;
	}

	@Column(name = "budget_id", nullable = false)
	public int getBudgetId() {
		return this.budgetId;
	}

	public void setBudgetId(int budgetId) {
		this.budgetId = budgetId;
	}

	@Column(name = "product_id", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BudgetDetailId))
			return false;
		BudgetDetailId castOther = (BudgetDetailId) other;

		return (this.getBudgetId() == castOther.getBudgetId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBudgetId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
