package entities;
<<<<<<< HEAD
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final
=======
// Generated 30 ene. 2020 8:50:01 by Hibernate Tools 5.2.12.Final
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * BudgetDetail generated by hbm2java
 */
@Entity
@Table(name = "budget_detail", catalog = "7057507_administration_db", uniqueConstraints = @UniqueConstraint(columnNames = "product_id"))
public class BudgetDetail implements java.io.Serializable {

	private BudgetDetailId id;
	private Integer budgetId;
	private Double quantity;
	private Double price;
	private Double priceUnit;
<<<<<<< HEAD

	public BudgetDetail() {
	}

	public BudgetDetail(BudgetDetailId id) {
		this.id = id;
	}

	public BudgetDetail(BudgetDetailId id, Integer budgetId, Double quantity, Double price, Double priceUnit) {
		this.id = id;
		this.budgetId = budgetId;
=======
	
	private IntegerProperty id_prop = new SimpleIntegerProperty(); 
	private ObjectProperty<Budget> budget_prop = new SimpleObjectProperty<>(); 
	private ObjectProperty<Product> product_prop = new SimpleObjectProperty<>(); 
	private DoubleProperty quantity_prop = new SimpleDoubleProperty(); 
	private DoubleProperty price_prop = new SimpleDoubleProperty();
	private DoubleProperty priceUnit_prop = new SimpleDoubleProperty(); 
	
	

	public BudgetDetail(Integer id, Budget budget, Product product, Double quantity, Double price, Double priceUnit,
			IntegerProperty id_prop, ObjectProperty<Budget> budget_prop, ObjectProperty<Product> product_prop,
			DoubleProperty quantity_prop, DoubleProperty price_prop, DoubleProperty priceUnit_prop) {
		super();
		this.id = id;
		this.budget = budget;
		this.product = product;
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
		this.quantity = quantity;
		this.price = price;
		this.priceUnit = priceUnit;
		
		try {this.id_prop.set(id);} catch (Exception e) {}
		try {this.budget_prop.set(budget);} catch (Exception e) {}
		try {this.product_prop.set(product);} catch (Exception e) {}
		try {this.quantity_prop.set(quantity);} catch (Exception e) {}
		try {this.price_prop.set(price);} catch (Exception e) {}
		try {this.priceUnit_prop.set(priceUnit);} catch (Exception e) {}
		
		
	}

<<<<<<< HEAD
	@EmbeddedId
=======

	public BudgetDetail() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003

	@AttributeOverrides({
			@AttributeOverride(name = "budgetDetailId", column = @Column(name = "budget_detail_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 30)) })
	public BudgetDetailId getId() {
		return this.id;
	}

	public void setId(BudgetDetailId id) {
		this.id = id;
		this.id_prop.set(id);
	}

<<<<<<< HEAD
	@Column(name = "budget_id")
	public Integer getBudgetId() {
		return this.budgetId;
	}

	public void setBudgetId(Integer budgetId) {
		this.budgetId = budgetId;
=======
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "budget_id")
	public Budget getBudget() {
		return this.budget;
	}

	public void setBudget(Budget budget) {
		this.budget = budget;
		this.budget_prop.set(budget);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", unique = true)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
		this.product_prop.set(product);
>>>>>>> dae55e6b1c545256e284754ebc17ecc715251003
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
		this.quantity_prop.set(quantity);
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
		this.price_prop.set(price);
	}

	@Column(name = "price_unit", precision = 22, scale = 0)
	public Double getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(Double priceUnit) {
		this.priceUnit = priceUnit;
		this.priceUnit_prop.set(priceUnit);
	}
	
	
	//JavaFX Getters & Setters
	
	
	public final IntegerProperty id_propProperty() {
		return this.id_prop;
	}
	

	public final ObjectProperty<Budget> budget_propProperty() {
		return this.budget_prop;
	}
	


	public final ObjectProperty<Product> product_propProperty() {
		return this.product_prop;
	}
	

	public final DoubleProperty quantity_propProperty() {
		return this.quantity_prop;
	}
	

	public final DoubleProperty price_propProperty() {
		return this.price_prop;
	}
	

	public final DoubleProperty priceUnit_propProperty() {
		return this.priceUnit_prop;
	}	
	
	

}
