package entities;
// Generated 19 ene. 2020 16:41:53 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InvoiceDetail generated by hbm2java
 */
@Entity
@Table(name = "invoice_detail", catalog = "7057507_administration_db")
public class InvoiceDetail implements java.io.Serializable {

	private InvoiceDetailId id;
	private Double quantity;
	private Double price;

	public InvoiceDetail() {
	}

	public InvoiceDetail(InvoiceDetailId id) {
		this.id = id;
	}

	public InvoiceDetail(InvoiceDetailId id, Double quantity, Double price) {
		this.id = id;
		this.quantity = quantity;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "invoice_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 30)) })
	public InvoiceDetailId getId() {
		return this.id;
	}

	public void setId(InvoiceDetailId id) {
		this.id = id;
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
