package entities;
// Generated 21 ene. 2020 12:50:14 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PayMethod generated by hbm2java
 */
@Entity
@Table(name = "pay_method", catalog = "7057507_administration_db")
public class PayMethod implements java.io.Serializable {

	private Integer payMethodId;
	private String description;

	public PayMethod() {
	}

	public PayMethod(String description) {
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pay_method_id", unique = true, nullable = false)
	public Integer getPayMethodId() {
		return this.payMethodId;
	}

	public void setPayMethodId(Integer payMethodId) {
		this.payMethodId = payMethodId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
