package entities;
// Generated 21 ene. 2020 12:50:14 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorkOrderDetailId generated by hbm2java
 */
@Embeddable
public class WorkOrderDetailId implements java.io.Serializable {

	private int orderDetailId;
	private String productId;

	public WorkOrderDetailId() {
	}

	public WorkOrderDetailId(int orderDetailId, String productId) {
		this.orderDetailId = orderDetailId;
		this.productId = productId;
	}

	@Column(name = "order_detail_id", nullable = false)
	public int getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(int orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@Column(name = "product_id", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkOrderDetailId))
			return false;
		WorkOrderDetailId castOther = (WorkOrderDetailId) other;

		return (this.getOrderDetailId() == castOther.getOrderDetailId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderDetailId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
