package entities;
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorkOrderDetailId generated by hbm2java
 */
@Embeddable
public class WorkOrderDetailId implements java.io.Serializable {

	private int workOrderDetailId;
	private String productId;

	public WorkOrderDetailId() {
	}

	public WorkOrderDetailId(int workOrderDetailId, String productId) {
		this.workOrderDetailId = workOrderDetailId;
		this.productId = productId;
	}

	@Column(name = "work_order_detail_id", nullable = false)
	public int getWorkOrderDetailId() {
		return this.workOrderDetailId;
	}

	public void setWorkOrderDetailId(int workOrderDetailId) {
		this.workOrderDetailId = workOrderDetailId;
	}

	@Column(name = "product_id", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkOrderDetailId))
			return false;
		WorkOrderDetailId castOther = (WorkOrderDetailId) other;

		return (this.getWorkOrderDetailId() == castOther.getWorkOrderDetailId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkOrderDetailId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
