package entities;
// Generated 19 ene. 2020 16:41:53 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkOrder generated by hbm2java
 */
@Entity
@Table(name = "work_order", catalog = "7057507_administration_db")
public class WorkOrder implements java.io.Serializable {

	private Integer workOrderId;
	private String companyId;
	private String customerId;
	private Date workOrderDate;
	private Integer status;
	private Integer conceptId;
	private Double price;
	private String taxId;
	private Double taxTotal;
	private Double priceTaxesIncluded;

	public WorkOrder() {
	}

	public WorkOrder(String companyId, String customerId, Date workOrderDate, Integer status, Integer conceptId,
			Double price, String taxId, Double taxTotal, Double priceTaxesIncluded) {
		this.companyId = companyId;
		this.customerId = customerId;
		this.workOrderDate = workOrderDate;
		this.status = status;
		this.conceptId = conceptId;
		this.price = price;
		this.taxId = taxId;
		this.taxTotal = taxTotal;
		this.priceTaxesIncluded = priceTaxesIncluded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "work_order_id", unique = true, nullable = false)
	public Integer getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(Integer workOrderId) {
		this.workOrderId = workOrderId;
	}

	@Column(name = "company_id")
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "customer_id")
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "work_order_date", length = 10)
	public Date getWorkOrderDate() {
		return this.workOrderDate;
	}

	public void setWorkOrderDate(Date workOrderDate) {
		this.workOrderDate = workOrderDate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "concept_id")
	public Integer getConceptId() {
		return this.conceptId;
	}

	public void setConceptId(Integer conceptId) {
		this.conceptId = conceptId;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "tax_id", length = 30)
	public String getTaxId() {
		return this.taxId;
	}

	public void setTaxId(String taxId) {
		this.taxId = taxId;
	}

	@Column(name = "tax_total", precision = 22, scale = 0)
	public Double getTaxTotal() {
		return this.taxTotal;
	}

	public void setTaxTotal(Double taxTotal) {
		this.taxTotal = taxTotal;
	}

	@Column(name = "price_taxes_included", precision = 22, scale = 0)
	public Double getPriceTaxesIncluded() {
		return this.priceTaxesIncluded;
	}

	public void setPriceTaxesIncluded(Double priceTaxesIncluded) {
		this.priceTaxesIncluded = priceTaxesIncluded;
	}

}
