package entities;
// Generated 19 ene. 2020 16:41:53 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WorkOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "work_order_detail", catalog = "7057507_administration_db")
public class WorkOrderDetail implements java.io.Serializable {

	private WorkOrderDetailId id;
	private Double quantity;
	private Double price;

	public WorkOrderDetail() {
	}

	public WorkOrderDetail(WorkOrderDetailId id) {
		this.id = id;
	}

	public WorkOrderDetail(WorkOrderDetailId id, Double quantity, Double price) {
		this.id = id;
		this.quantity = quantity;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "workOrderId", column = @Column(name = "work_order_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 30)) })
	public WorkOrderDetailId getId() {
		return this.id;
	}

	public void setId(WorkOrderDetailId id) {
		this.id = id;
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
