package entities;
// Generated 24 ene. 2020 9:53:08 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WorkOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "work_order_detail", catalog = "7057507_administration_db")
public class WorkOrderDetail implements java.io.Serializable {

	private WorkOrderDetailId id;
	private Integer workOrderId;
	private Double quantity;
	private Double price;
	private Double priceUnit;

	public WorkOrderDetail() {
	}

	public WorkOrderDetail(WorkOrderDetailId id) {
		this.id = id;
	}

	public WorkOrderDetail(WorkOrderDetailId id, Integer workOrderId, Double quantity, Double price, Double priceUnit) {
		this.id = id;
		this.workOrderId = workOrderId;
		this.quantity = quantity;
		this.price = price;
		this.priceUnit = priceUnit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderDetailId", column = @Column(name = "order_detail_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 30)) })
	public WorkOrderDetailId getId() {
		return this.id;
	}

	public void setId(WorkOrderDetailId id) {
		this.id = id;
	}

	@Column(name = "work_order_id")
	public Integer getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(Integer workOrderId) {
		this.workOrderId = workOrderId;
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "price_unit", precision = 22, scale = 0)
	public Double getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(Double priceUnit) {
		this.priceUnit = priceUnit;
	}

}
