package entities;
// Generated 19 ene. 2020 16:41:53 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorkOrderDetailId generated by hbm2java
 */
@Embeddable
public class WorkOrderDetailId implements java.io.Serializable {

	private int workOrderId;
	private String productId;

	public WorkOrderDetailId() {
	}

	public WorkOrderDetailId(int workOrderId, String productId) {
		this.workOrderId = workOrderId;
		this.productId = productId;
	}

	@Column(name = "work_order_id", nullable = false)
	public int getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(int workOrderId) {
		this.workOrderId = workOrderId;
	}

	@Column(name = "product_id", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkOrderDetailId))
			return false;
		WorkOrderDetailId castOther = (WorkOrderDetailId) other;

		return (this.getWorkOrderId() == castOther.getWorkOrderId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkOrderId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
