package entities;
// Generated 25 ene. 2020 22:19:24 by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Concept generated by hbm2java
 */
@Entity
@Table(name = "concept", catalog = "7057507_administration_db")
public class Concept implements java.io.Serializable {

	private Integer id;
	private String description;
	private Double price;
	private List<Budget> budgets = new ArrayList<Budget>(0);
	private List<Invoice> invoices = new ArrayList<Invoice>(0);
	private List<WorkOrder> workOrders = new ArrayList<WorkOrder>(0);

	public Concept() {
	}

	public Concept(String description, Double price, List<Budget> budgets, List<Invoice> invoices,
			List<WorkOrder> workOrders) {
		this.description = description;
		this.price = price;
		this.budgets = budgets;
		this.invoices = invoices;
		this.workOrders = workOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 600)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concept")
	public List<Budget> getBudgets() {
		return this.budgets;
	}

	public void setBudgets(List<Budget> budgets) {
		this.budgets = budgets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concept")
	public List<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(List<Invoice> invoices) {
		this.invoices = invoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concept")
	public List<WorkOrder> getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(List<WorkOrder> workOrders) {
		this.workOrders = workOrders;
	}

}
